"""Bundle the supplied samples and real Git diffs for the offline demo (stdlib only)."""
import hashlib
import json
import subprocess
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SAMPLES = ROOT.parent / "sample-data"
PLAYBOOK = "Azure 预留交换策略的变化.md"


def git_diff(before, after, name):
    with tempfile.TemporaryDirectory(prefix="21v-demo-") as temp:
        folder = Path(temp)
        for side, content in [("a", before), ("b", after)]:
            (folder / side).mkdir()
            (folder / side / name).write_bytes(content.encode("utf-8"))
        result = subprocess.run(
            ["git", "-c", "core.quotePath=false", "diff", "--no-index", "--no-ext-diff", "--no-color", "--text", "--", "a/" + name, "b/" + name],
            cwd=folder, capture_output=True, text=True,
        )
        if result.returncode not in (0, 1):
            raise RuntimeError(result.stderr)
        return result.stdout.replace("a/a/", "a/").replace("b/b/", "b/")


def main():
    sources = {}
    for key, name, title, kb in [
        ("mysql", "mysql.json", "Azure Database for MySQL 定价", "acn"),
        ("playbook", PLAYBOOK, "Azure 预留交换策略的变化", "playbook"),
    ]:
        original = (SAMPLES / name).read_bytes()
        raw = original.decode("utf-8")
        if key == "mysql":
            assert raw.count("0.1449") >= 1
            updated = raw.replace("0.1449", "0.1594", 1)
            conflict = raw.replace("0.1449", "0.1390", 1)
            label = "中国北部 3 · B1MS 演示调价"
            explanation = "仅修改中国北部 3 的 B1MS 小时单价：0.1449 → 0.1594。此变动为演示构造，不代表真实报价。"
        else:
            updated = raw + "\r\n\r\n#### 16. 内部执行检查清单（演示修订）\r\n\r\n> 以下为功能演示新增的内部流程，不是 Azure 官方政策。\r\n\r\n* 核对预留的购买日期、服务类型和剩余交换次数。\r\n* 在项目工单中记录目标规格、区域和费用评估。\r\n* 由项目负责人确认后提交申请，并保留交换结果。\r\n"
            conflict = updated.replace("由项目负责人确认", "由部门负责人确认")
            label = "新增内部执行检查清单"
            explanation = "保留原文政策和日期，新增第 16 节内部检查清单。新增内容已明确标注为演示修订。"
        sources[key] = {
            "id": key, "name": name, "title": title, "kbId": kb,
            "format": name.rsplit(".", 1)[-1], "raw": raw,
            "sha256": hashlib.sha256(original).hexdigest(),
            "updated": updated, "conflict": conflict, "label": label,
            "explanation": explanation,
            "diff": git_diff(raw, updated, name),
            "conflictDiff": git_diff(raw, conflict, name),
        }
    output = "// Generated by prepare_data.py. Original sample bytes are preserved in raw.\nwindow.DEMO_DATA = " + json.dumps(sources, ensure_ascii=False) + ";\n"
    (ROOT / "data.js").write_text(output, encoding="utf-8")
    print("Bundled 2 original samples, 4 demonstration revisions and their Git diffs.")


if __name__ == "__main__":
    main()
